/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
  IsDate,
  IsInt,
  Min,
  Max,
} from "class-validator";
import { ChatCreateNestedManyWithoutLivestreamsInput } from "./ChatCreateNestedManyWithoutLivestreamsInput";
import { Type } from "class-transformer";
import { DonationCreateNestedManyWithoutLivestreamsInput } from "./DonationCreateNestedManyWithoutLivestreamsInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class LivestreamCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  category?: string | null;

  @ApiProperty({
    required: false,
    type: () => ChatCreateNestedManyWithoutLivestreamsInput,
  })
  @ValidateNested()
  @Type(() => ChatCreateNestedManyWithoutLivestreamsInput)
  @IsOptional()
  @Field(() => ChatCreateNestedManyWithoutLivestreamsInput, {
    nullable: true,
  })
  chats?: ChatCreateNestedManyWithoutLivestreamsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => DonationCreateNestedManyWithoutLivestreamsInput,
  })
  @ValidateNested()
  @Type(() => DonationCreateNestedManyWithoutLivestreamsInput)
  @IsOptional()
  @Field(() => DonationCreateNestedManyWithoutLivestreamsInput, {
    nullable: true,
  })
  donations?: DonationCreateNestedManyWithoutLivestreamsInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  endTime?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  recordingUrl?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  startTime?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  status?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  viewerCount?: number | null;
}

export { LivestreamCreateInput as LivestreamCreateInput };
