/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
  IsBoolean,
} from "class-validator";
import { ChatCreateNestedManyWithoutUsersInput } from "./ChatCreateNestedManyWithoutUsersInput";
import { Type } from "class-transformer";
import { DonationCreateNestedManyWithoutUsersInput } from "./DonationCreateNestedManyWithoutUsersInput";
import { LivestreamCreateNestedManyWithoutUsersInput } from "./LivestreamCreateNestedManyWithoutUsersInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  bio?: string | null;

  @ApiProperty({
    required: false,
    type: () => ChatCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ChatCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ChatCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  chats?: ChatCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => DonationCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => DonationCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => DonationCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  donations?: DonationCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isBlocked?: boolean | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: () => LivestreamCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => LivestreamCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => LivestreamCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  livestreams?: LivestreamCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  profilePicture?: string | null;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;
}

export { UserCreateInput as UserCreateInput };
