/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { ChatUpdateManyWithoutUsersInput } from "./ChatUpdateManyWithoutUsersInput";
import { Type } from "class-transformer";
import { DonationUpdateManyWithoutUsersInput } from "./DonationUpdateManyWithoutUsersInput";
import { LivestreamUpdateManyWithoutUsersInput } from "./LivestreamUpdateManyWithoutUsersInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";

@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  bio?: string | null;

  @ApiProperty({
    required: false,
    type: () => ChatUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ChatUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ChatUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  chats?: ChatUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => DonationUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => DonationUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => DonationUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  donations?: DonationUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: () => LivestreamUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => LivestreamUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => LivestreamUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  livestreams?: LivestreamUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  profilePicture?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  roles?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;
}

export { UserUpdateInput as UserUpdateInput };
